variable "project_name" {
  description = "Short project identifier, used as a prefix on all resource names."
  type        = string
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)."
  type        = string
}

variable "vpc_link_sg_id" {
  description = "Security group ID attached to VPC Link ENIs. Must allow outbound TCP to the ECS tasks security group."
  type        = string
}

variable "subnet_ids" {
  description = "Subnet IDs where VPC Link ENIs are placed. Must be within the same VPC as ECS tasks."
  type        = list(string)
}

variable "internal_token" {
  description = "Shared secret injected as X-Internal-Token on every forwarded request. Downstream services validate this header to confirm requests arrived via API Gateway. Generated by Terraform and stored in SSM — never hardcoded. See api-gateway-trust.md."
  type        = string
  sensitive   = true
}

variable "log_retention_days" {
  description = "CloudWatch log retention in days for API Gateway access logs."
  type        = number
  default     = 7
}
