variable "project_name" {
  description = "Short project identifier, used as a prefix on all resource names."
  type        = string
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)."
  type        = string
}

variable "vpc_link_sg_id" {
  description = "Security group ID attached to VPC Link ENIs. Must allow outbound TCP to the ECS tasks security group."
  type        = string
}

variable "subnet_ids" {
  description = "Subnet IDs where VPC Link ENIs are placed. Must be within the same VPC as ECS tasks."
  type        = list(string)
}

variable "jwt_issuer" {
  description = "Issuer claim (iss) the JWT Authorizer validates against. Must match what auth-workspace sets in issued JWTs. Use a fixed per-environment string — not the API Gateway URL, which changes on each dev-down/dev-up. See ADR-026."
  type        = string
}

variable "jwt_audience" {
  description = "Audience claim (aud) the JWT Authorizer validates against. Must match what auth-workspace sets in issued JWTs."
  type        = string
  default     = "collabspace-api"
}

variable "internal_token" {
  description = "Shared secret injected as X-Internal-Token on every forwarded request. Downstream services validate this header to confirm requests arrived via API Gateway. Generated by Terraform and stored in SSM — never hardcoded. See api-gateway-trust.md."
  type        = string
  sensitive   = true
}
